#!/usr/bin/env bash
# Mostrar las horas y minutos en las primeras 70 lineas

hour=0
while [ $hour -le 12 ];
do
    echo "Hour: $hour"
    (( hour=hour+1 ))

    minutes=1
    while [ $minutes -le 59 ];
    do
	echo  $minutes
	(( minutes=minutes+1 ))	
    done
done

